export enum IconType {
    HOMESOLID = "fa-solid fa-house ",
    LOGOUTSOLID = "fa-solid fa-left-from-bracket ",
    AUTOCLUSRETSOLID = "fa-solid fa-list ",
    REPORTSOLID = "fa-solid fa-chart-line-up ",
    NEWCLUSTERSOLID = "fa-solid fa-plus ",
    HOMELIGHT = "fa-light fa-house ",
    LOGOUTLIGHT = "fa-light fa-left-from-bracket ",
    AUTOCLUSRETLIGHT = "fa-light fa-list ",
    REPORTLIGHT = "fa-light fa-chart-line-up ",
    // NEWCLUSTERLIGHT = "fa-light fa-plus ",
    ROTATERIGHT = "fa-light fa-arrow-rotate-right ",
    ROTATELEFT = "fa-light fa-arrow-rotate-left ",
    PRINT = "fa-light fa-print ",
    ZOOMIN = "fa-light fa-magnifying-glass-minus ",
    ZOOMOUT = "fa-light fa-magnifying-glass-plus ",
    FOLDER_PLUS="fa-light fa-folder-plus",
    LAYER_PLUS="fa-light fa-layer-plus",
    PLUS="fa-light fa-plus",
    FILE_ARROW_DOWN="fa-light fa-file-arrow-down",
    CHEVRON_LEFT="fa-light fa-chevron-left"   
}